# Source: cloudnative-pg/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnpg-cloudnative-pg
  namespace: cnpg-system
  labels:
    helm.sh/chart: cloudnative-pg-0.23.2
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/version: "1.25.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
      app.kubernetes.io/instance: cnpg
  template:
    metadata:
      annotations:
        checksum/rbac: 52a816417de47a05cd0449212c52a45314cd27ab4c17188a81376d18e92fe50d
        checksum/config: 8aed98a58ec7d26eea4637359e814c14d704c7e709a3cbd93dc4546ca06dab9a
        checksum/monitoring-config: 9a6b17455d5a86102be8ca04d0b275d6c84cb28192ddb1c553df6202cbc841e0
      labels:
        app.kubernetes.io/name: cloudnative-pg
        app.kubernetes.io/instance: cnpg
    spec:
      containers:
      - args:
        - controller
        - --leader-elect
        - --max-concurrent-reconciles=10
        - --config-map-name=cnpg-controller-manager-config
        - --webhook-port=9443
        command:
        - /manager
        env:
        - name: OPERATOR_IMAGE_NAME
          value: "ghcr.io/cloudnative-pg/cloudnative-pg:1.25.1"
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MONITORING_QUERIES_CONFIGMAP
          value: "cnpg-default-monitoring"
        image: "ghcr.io/cloudnative-pg/cloudnative-pg:1.25.1"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /readyz
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 3
        name: manager
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 3
        resources:
          {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          failureThreshold: 6
          httpGet:
            path: /readyz
            port: 9443
            scheme: HTTPS
          periodSeconds: 5
        volumeMounts:
        - mountPath: /controller
          name: scratch-data
        - mountPath: /run/secrets/cnpg.io/webhook
          name: webhook-certificates
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: cnpg-cloudnative-pg
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: scratch-data
      - name: webhook-certificates
        secret:
          defaultMode: 420
          optional: true
          secretName: cnpg-webhook-cert
