# Source: cloudnative-pg/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cnpg-webhook-service
  namespace: cnpg-system
  labels:
    helm.sh/chart: cloudnative-pg-0.23.2
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/version: "1.25.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: webhook-server
    name: webhook-server
  selector:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/instance: cnpg
