# Source: cloudnative-pg/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnpg-cloudnative-pg
  namespace: cnpg-system
  labels:
    helm.sh/chart: cloudnative-pg-0.23.2
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/version: "1.25.1"
    app.kubernetes.io/managed-by: Helm
