apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: usdf-maf-opsim-backup
  namespace: opsim
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: usdf-maf-opsim
